# Generated by Django 4.2.30 on 2026-09-11 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesettings',
            name='battle_end',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 15, 12, 0, tzinfo=datetime.timezone.utc), verbose_name='Конец баттла'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Затраченное время (сек)'),
        ),
        migrations.AlterField(
            model_name='battlesettings',
            name='battle_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 15, 10, 0, tzinfo=datetime.timezone.utc), verbose_name='Начало баттла'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='execution_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время выполнения БД (мс)'),
        ),
    ]
